### ISSUE TITLE
Add method to save login

### ISSUE THREAD

**Issue by flameoflust69** [rugantio/fbcrawl#21]
So Facebook save login cookies inside c_user, fr and xs. Is there any way we can save cookies login? So we dont have to login each time run a scrapper.

**Comment by rugantio** [comment]
Hi @flameoflust69!
Yes, the way to do this is to use a custom designed cookies middleware because the one build with scrapy is programmed to keep the cookies only between different requests of the same session.
Luckily this was already coded in a very nice and clear way here: https://github.com/grammy-jiang/scrapy-cookies
